Change to single drift chamber and modify the percentage of gas elements
cepc/CEPCSW pull request #165
Opened 2021-05-08 12:52 UTC by myliu-hub

Change the dual drift chamber to a single drift chamber, where
1. inner radius:800mm
2. outer radius:1720mm
The radii of the inner and outer walls respectively extend outward.
  Due to the modification of the inner and outer radius of the drift chamber, the parameters of the silicon detector should also be corrected accordingly. Since I am not clear, I added the parameters of the single drift chamber in the `Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml` and `Detector/DetCRD/compact/CRD_o1_v02/CRD_Dimensions_v01_02.xml` , and the parameters of the dual drift chamber were not deleted before.

2021-05-08 12:54 UTC, myliu-hub commented
@fucd ,Would you please check if this is reasonable?

2021-05-10 01:20 UTC, fucd commented
@myliu-hub Do you decide to replace the cpp file not create a new one with version number?

2021-05-11 02:00 UTC, fucd commented on Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml
> +    <constant name="world_size" value="2226*mm"/>
not used? And world should not be defined in sub-detector option file.

2021-05-11 02:03 UTC, fucd commented on Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml
> +    <constant name="DetID_DC"  value="7"/>
has defined in CRD_Dimensions_v01_01.xml

2021-05-11 02:06 UTC, fucd commented on Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml
> +       author="C.D.Fu, "
any contributor can be added here

2021-05-11 02:12 UTC, fucd commented on Detector/DetCRD/compact/CRD_o1_v01/CRD_Dimensions_v01_01.xml
> +    <constant name="Tracker_half_length"  value="DC_half_length" />
Tracker is a prefix easy to confuse. Can you rename it?

2021-05-11 14:34 UTC, myliu-hub commented
Change the dual drift chamber to a single drift chamber, where

inner radius:800mm
outer radius:1720mm

@fucd， I made some modifications based on your suggestions. At the same time, due to the change of the radius, there will be an overlap with the silicon detector. You may need to update the silicon detector later.

2021-05-12 01:30 UTC, myliu-hub commented
Sorry, the outer radius is 1800mm

2021-05-19 01:33 UTC, mirguest requested changes
Hi @myliu-hub , please have a look at my comments. 
Thank you.
Tao

2021-05-19 01:33 UTC, mirguest commented on Detector/DetDriftChamber/compact/det.xml
> +    <constant name="SDT_radius_max" value="1803*mm"/>
Hi @myliu-hub , I think these value should not be hardcoded.

Tao

2021-05-19 01:33 UTC, mirguest commented on Detector/DetDriftChamber/src/driftchamber/DriftChamber.cpp
> +    det_chamber_phy.addPhysVolID("chamber", 0);
For the chamber id, you should avoid the hardcoded number. 
Maybe the hardware groups need the multiple chambers in the future. 

Tao

2021-05-19 15:10 UTC, mirguest requested changes

2021-05-19 15:10 UTC, mirguest commented on Detector/DetCRD/compact/CRD_common_v01/DC_Simple_v01_01.xml
>        <envelope vis="SeeThrough">
Hi @myliu-hub ,
As you already add the chamber id, do you need to update this part? Or you already define the default value?
Tao

2021-05-20 01:51 UTC, mirguest approved these changes

2021-05-20 01:51 UTC, merged