add TrackHeedSimTool
cepc/CEPCSW pull request #178
Opened 2021-09-01 09:49 UTC by wenxingfang

add TrackHeedSimTool to do ionization for drift chamber for issue #177

2021-09-01 09:57 UTC, mirguest requested changes

2021-09-01 09:57 UTC, mirguest commented on Simulation/DetSimDedx/CMakeLists.txt
> +include_directories("/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/98.0.0/Garfield++/include/")
It should be avoided to hard code the paths. Please rewrite this part.

2021-09-06 02:57 UTC, mirguest commented
Hi @wenxingfang ,
I have just created a PR https://github.com/spack/spack/pull/25800 in spack. After the package is merged, I will notify the maintainers of key4hep-spack.
Tao

2021-09-06 10:30 UTC, wenxingfang commented
@mirguest I have merged master branch of CEPCSW, but the build is still cancelled.

2021-09-06 12:31 UTC, mirguest commented
> @mirguest I have merged master branch of CEPCSW, but the build is still cancelled.

Maybe the spack job failed, then the jobs are cancelled.

2021-10-08 08:29 UTC, closed without merging