Add CRD Ecal geometry
cepc/CEPCSW pull request #32
Opened 2020-09-15 07:32 UTC by qwert2333

2020-09-15 09:58 UTC, mirguest commented
Hi @qwert2333 , 
Please add detail description of your geometry in this PR. 
If possible, you could upload a snapshot of the ECAL.

Tao

2020-09-15 12:08 UTC, mirguest commented on Detector/DetCRD/compact/ecalBarrel.xml
> +      <id>block:8,layer:12,piece:12,bar:12</id>
@qwert2333 @LinghuiWuIHEP

Please note that you should have `system` field defined in this ID definition.

Tao

2020-09-16 09:48 UTC, qwert2333 commented
Detector description(DD4hep): 
  First version v0r0: full BGO crystal in all detector. 
  Geometry: 
    Global (could be modified in ecalBarrel.xml)
        Inner radius: 1800mm. 
        Z length: 4600mm. 
        Thickness: 280mm. ( ! Must be integer multiple of 10).
    Crystal bars placement: 
        Bar size:  1cm*1cm*~40cm  ( 1cm*1cm is hard-coding in CRDEcal.cpp ).
        Odd layer: along with phi direction, 3~5 bars in each layer.     ( ! Number of bars is Hard-coding )
        Even layer: along with Z axis, 12 bars in layer.    ( ! Number of bars is fixed to 12) 
  Cell ID: 
    system: 4 bit.  (8 parts)  
    layer: 6 bit    (~28 layers)
    block: 8bit    (<200 bars in phi direction)
    bar: 10 bit     ( max~460 bars in Z direction)

2020-09-18 12:18 UTC, mirguest requested changes
Please make sure your code is well format.

2020-09-18 12:18 UTC, mirguest commented on Detector/DetCRD/src/Calorimeter/CRDEcal.cpp
> +    std::string det_name = x_det.nameStr();
In CRDEcal.cpp, please make sure Tabs and Spaces are not mixed.
Please consider using 4 space for indentation.

2020-09-18 15:36 UTC, fucd commented
Hi @qwert2333 

My suggestion is that don't use Tube to create envelope, but PolyhedraRegular. Because to put other detector components into space between  PolyhedraRegular and Tube is possibly required. 
`dd4hep::Tube		envelope(R0, (R0+h0)/cos(22.5*degree), Z0/2, 0, 2*M_PI);`

Chengdong

2020-10-16 08:59 UTC, merged