WIP: Transmission of data type(required to test)
cepc/CEPCSW pull request #42
Opened 2020-09-17 14:53 UTC by zhaomr13

Hi @mirguest ,

Could you please review the code and  test the building?
If it is ok, I will test the performance of this part with the help of Chengdong @fucd 

Mingrui.

2020-09-18 01:15 UTC, mirguest commented
Hi Mingrui, 
Do you have any special settings? I found there is no build for your PR.
Tao

2020-09-18 05:11 UTC, zhaomr13 commented
Hi Tao @mirguest ,

I have no special setting. What do you mean "no build for your PR"? and what is PR?

Mingrui.

2020-09-18 05:54 UTC, mirguest commented
Hi Mingrui,
PR means Pull Request. We have setup Travis-CI to build all the PRs automatically. But it looks like that the CI does not trigger in your Pull Request.
Tao

2020-09-18 06:02 UTC, zhaomr13 commented
How could the CI be triggered? Could you help to check?

2020-09-18 12:40 UTC, mirguest commented
Hi Mingrui,
I have compiled your code and it looks fine. So I will merge your PR.
Tao

2020-09-18 12:42 UTC, mirguest commented on Service/TrackSystemSvc/TrackSystemSvc/MarlinTrkDiagnostics.h.remove
> -    EVENT::SimTrackerHit* simhit;
@zhaomr13 This file should be removed.

2020-09-18 12:43 UTC, mirguest commented on Service/TrackSystemSvc/src/DiagnosticsController.cc.remove
> -    EVENT::TrackerHit* trkhit = hit->getLCIOTrackerHit();
@zhaomr13 This file should be removed.

2020-09-18 12:43 UTC, mirguest requested changes
Please make sure the files such as `.remove` are removed.

2020-09-18 13:23 UTC, mirguest commented on Utilities/KiTrack/src/Tools/VXDHelixFitter.cc.bak
> -VXDHelixFitter::VXDHelixFitter( std::vector< TrackerHit* > trackerHits ){
Please remove this file.

2020-09-21 06:39 UTC, zhaomr13 commented
Hi Tao(@mirguest) ,

The files has been removed.

Mingrui.

2020-09-21 08:07 UTC, mirguest approved these changes

2020-09-21 08:08 UTC, merged

2020-09-21 08:09 UTC, mirguest commented
Hi @zhaomr13 
Thank you. It's merged now.
Tao